application:
  port: 8000
  host: 0.0.0.0
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: false
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "ozan.kececioglu@nirx.de"
  authorization_token: "bf4b2639-a89c-49c1-ba0c-42455a881f77"
  timeout_milliseconds: 10000